name: BioForge CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: cd frontend && npm ci
    
    - name: Run frontend tests
      run: cd frontend && npm test
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install backend dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run backend tests
      run: cd backend && pytest
  
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: bioforge/frontend:latest
    
    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: bioforge/backend:latest
    
    - name: Build and push AI service
      uses: docker/build-push-action@v4
      with:
        context: ./ai-service
        push: true
        tags: bioforge/ai-service:latest
    
    - name: Build and push safety service
      uses: docker/build-push-action@v4
      with:
        context: ./safety-service
        push: true
        tags: bioforge/safety-service:latest
    
    - name: Build and push simulation service
      uses: docker/build-push-action@v4
      with:
        context: ./simulation-service
        push: true
        tags: bioforge/simulation-service:latest
    
    - name: Build and push data pipelines
      uses: docker/build-push-action@v4
      with:
        context: ./data-pipelines
        push: true
        tags: bioforge/data-pipelines:latest
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - name: Deploy to server
      run: |
        scp docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/bioforge/
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/bioforge && docker-compose pull && docker-compose up -d"
